### ISSUE TITLE
My hackemon bot shows that it successfully log in but stops there

### ISSUE THREAD

**Issue by Beatzboy** [Nader-Sl/Hackemon#55] opened 2016-08-16 03:41 UTC
Hi, I run 2 bots using the same computer. For a day, it was running fine. But just since last night, my Bot will stop at a poke stop and that's it. The last message was that I receive 0 xp. It stops there. When I restart the bot. It only shows that it successfully log in and that's it. Anybody face this issue?

**Comment by VXT108** [comment] 2016-08-16 04:15
It might be an IP ban. Have you tried using a proxy or VPN?

**Comment by Beatzboy** [comment] 2016-08-16 05:02
Oh no I have not. Maybe I can go and try. Thx a lot!

**Comment by pingpongplaya** [comment] 2016-08-16 05:07
same for me and I for sure don't have an IP ban lol

**Comment by pingpongplaya** [comment] 2016-08-16 05:08
confirmed, if you have a successfully log in and stopped there.. its the same as "fail to get data from server aka. a hard ban"

**Comment by Beatzboy** [comment] 2016-08-16 05:10
However, I still can log in using the Pokemon go app. And everything runs fine in there

**Comment by pingpongplaya** [comment] 2016-08-16 05:15
not in my cases 2 of my accounts got the same thing the hackemon saying it successfully logged in but not botting, got the login error. the other one which got softbanned from spinning pokestops working fine in hackemon. so... its the matter of time guys

**Comment by wEisB0145** [comment] 2016-08-16 08:34
i dont think its a hard ban. When my Bot does that, i close it, and connect to a VPN, and reopen it. Then it will work just fine (4 me at least)

**Comment by PokemonAddict** [comment] 2016-08-16 12:13
perma ban! check with phone ;)

**Comment by CrucifyAnkh** [comment] 2016-08-17 08:40
Hi, I didnt encounter any pokemon and it keep stated Appended incense poke PIDGEY etc

**Comment by Kirktonic** [comment] 2016-08-17 14:13
I am experiencing the same issue. This only happened after my Hackemon updated to V1.51. It randomly stops at a Pokestop and showing "[Pokestop Farm]: Gained 0 XP" and so I checked my account on my device and they are working fine. No soft or perma ban. Tried relaunching Hackemon and it sometimes continue botting and sometimes it is just stuck with the successful login message. The recent update may be causing this...

**Comment by wEisB0145** [comment] 2016-08-17 14:14
Can you loot Pokestops / fight in gyms... have you testet that?

If you cant, you are softbanned

**Comment by Roadieee** [comment] 2016-08-17 14:41
My account was running fine under previous version. Upgraded to 1.51 today and started experiencing the same behavior as above (logs in, but doesn't do anything). I always start the bot at my house. I opened the real app from home and spun the pokestop across the street and got items, so my account is neither soft nor hard banned... 1.51 just won't start farming for some reason.

**Comment by Kirktonic** [comment] 2016-08-17 15:07
@wEisB0145 Yes, I can spin Pokestops, catch Pokemons and Battle Gyms. The Hackemon V1.51 works but randomly stops at any given time (As mentioned above). Not sure why.

**Comment by ciannaaperta** [comment] 2016-08-19 02:22
Stop repeating the IP or any-ban issue. IT'S NOT. We are all stuck on THE SAME pokestop, which is of course empty because we (our bot) just spinned it. Will eventually take new items and exp after minutes stuck there. The problem is that the bot is not MOVING TO THE NEXT pokestop. It's stuck on the EMPTY pokestop it just spinned. NO BAN. Just the bot stuck in there. Keeps going to the nearer pokestop no matter it's been used. Is there a way to tell him to just skip to another pokestop?

**Closed** 2016-08-22 12:59 UTC
